### ISSUE TITLE
This is really nice and elegant. The repositories should be general, win-win is not recognised on mac

### ISSUE THREAD

**Issue by jawwada** [IQSS/IQSS.emacs#11]
This is really nice much better than bigger distributions, lean, and powerful. A couple of glitches on my man
win -win is not available and respositories should be changed to

package-archives '(("gnu" . "http://elpa.gnu.org/packages/")

                    ("org" . "http://orgmode.org/elpa/")

                    ("melpa" . "http://melpa.org/packages/")

                    ("melpa-stable" . "http://stable.melpa.org/packages/"))

package-archive-priorities '(("melpa-stable" . 1)))

**Comment by jawwada** [comment]
Oh Sorry, I noticed that copying init.el is not enough, should clone whole repo. Now it is even prettier. This is so good. A couple of things that I added include winum *for window numbering* and type script support. But this is as good (lean, humane and powerful) as emacs can get for a data scientist

**Comment by izahn** [comment]
@jawwada thanks for giving it a spin -- let me know if you find any rough spots.
