### ISSUE TITLE
typo in README.md and custom.el

### ISSUE THREAD

**Issue by grszkthfr** [IQSS/IQSS.emacs#12]
Hi,
thanks for providing such a nice .emacs.d.

I am completly new to emacs, there is one small typo in the customization section of the [README.md](https://github.com/IQSS/IQSS.emacs/blob/master/README.md#customization), which gave me some headaches...

`(add-to-list 'package-slected-packages 'matlab-mode)` should be `(add-to-list 'package-selected-packages 'matlab-mode)`

The same sneaked somehow into the custom.el with `;; (add-to-list 'package-slected-packages 'ess)` which should be `;; (add-to-list 'package-selected-packages 'ess)`.

Best Jonas

**Comment by izahn** [comment]
Fixed in https://github.com/IQSS/IQSS.emacs/pull/13 thank you @grszkthfr
