### ISSUE TITLE
ESS toolbar

### ISSUE THREAD

**Issue by napaxton** [IQSS/IQSS.emacs#16]
I like to have my toolbar enabled. But even with the global toolbar option turned on, using the IQSS init file, I don't get the toolbar "buttons" for ESS to show up. (LaTeX, on the other hand, does.) can you point me to the setting that's causing this behavior in this file?

**Comment by izahn** [comment]
I don't think this is caused by IQSS.emacs. At least for me the ESS toolbar doesn't work even with just plain vanilla Emacs. Does it work if you 

1. start with `emacs -1`
2. load packages with `M-x package-initialize`
2. open an R file

?

**Comment by napaxton** [comment]
Hmm. I tried switching to another init.el file (which does give me the icons). I can switch back and check tomorrow.

(emacs, btw, didn't care for the -1 option: "command-line-1: Unknown option ‘-1".)

**Comment by izahn** [comment]
Sorry for the typo, I meant "start with `emacs -q`".

I think I've found the problem though, should be fixed in https://github.com/IQSS/IQSS.emacs/commit/235483a690331cd5ab157094fa4314c9539bc59a

Can you test and let me know if it works?

**Comment by napaxton** [comment]
I think that did it, by Jove!
