### ISSUE TITLE
A list of the packages we always want (setq package-selected-packages)

### ISSUE THREAD

**Issue by AtomicNess123** [IQSS/IQSS.emacs#17]
Hi, 

What is the usefulness of overriding the value of this variable, as you have it in your init file?

`(setq package-selected-packages...)`

Thanks, 
GM

**Comment by izahn** [comment]
The basic idea is that we list all packages we want to install, and then install them with

```
(unless (every 'package-installed-p package-selected-packages)
  (package-refresh-contents)
  (package-install-selected-packages))
```

That happens both in `init.el` and in `custom.el`. If that doesn't answer your question please give some more details about what you want to know.

**Comment by AtomicNess123** [comment]
Thanks. Do you mean I must have those lines of code after `(setq package-selected-packages...)`.
I'm new in Emacs, and a friend configured my init file.
I am now going through it and found that line at the beginning of the init, and was wondering whether I should remove it. I have since then installed other packages that I manually at by adding individual setq ´nameofpackage. So I wonder if I should add them inside the `(setq package-selected-packages...)` or not. Sorry about my bad English!

**Comment by izahn** [comment]
Got it, and welcome to Emacs! Just add your packages in the `custom.el` file as described in the README at https://github.com/IQSS/IQSS.emacs#customization

**Comment by AtomicNess123** [comment]
Thanks a lot.
