### ISSUE TITLE
First run finishing with error

### ISSUE THREAD

**Issue by abunavas** [IQSS/IQSS.emacs#18]
I had this error in first run

`
Warning (bytecomp): reference to free variable ‘mc/cycle’
Warning (bytecomp): the following functions are not known to be defined: mc/cursor-beg,
    mc/cursor-end, return-from
Warning (bytecomp): ‘set-temporary-overlay-map’ is an obsolete function (as of 24.4); use ‘set-transient-map’ instead.
Warning (bytecomp): looking-back called with 1 argument, but requires 2-3
Warning (bytecomp): the following functions are not known to be defined:
    sgml-get-context, sgml-skip-tag-forward
Warning (bytecomp): defcustom for ‘mc/mode-line’ fails to specify type [2 times]
Warning (bytecomp): defcustom for ‘query-replace-from-to-separator’ fails to specify containing group
Warning (bytecomp): assignment to free variable ‘vr--is-emacs24’
Warning (bytecomp): misplaced interactive spec: ‘(interactive (vr--interactive-get-args (quote vr--mode-regexp) (quote vr--calling-func-mc-mark)))’
Warning (bytecomp): reference to free variable ‘clm/log-command-exceptions*’
Warning (bytecomp): defgroup for ‘command-log’ fails to specify containing group
Warning (bytecomp): assignment to free variable ‘ido-enable-flex-matching’
Warning (bytecomp): assignment to free variable ‘apropos-do-all’
Warning (bytecomp): assignment to free variable ‘ediff-window-setup-function’
Warning (bytecomp): the function ‘html2text’ is not known to be defined.
Warning (bytecomp): reference to free variable ‘ecb-activated-window-configuration’
Warning (bytecomp): reference to free variable ‘path’
Warning (bytecomp): reference to free variable ‘path-method’
Warning (bytecomp): reference to free variable ‘tramp-methods’
Warning (bytecomp): reference to free variable ‘path-user’
Warning (bytecomp): reference to free variable ‘path-host’
Warning (bytecomp): reference to free variable ‘path-localname’
Warning (bytecomp): the following functions are not known to be defined: ecb-deactivate,
    ecb-activate, tramp-tramp-file-p, with-parsed-tramp-file-name
Warning (bytecomp): ‘show-branches’ is an obsolete function (as of 25.1); use ‘outline-show-branches’ instead.
Warning (bytecomp): ‘show-all’ is an obsolete function (as of 25.1); use ‘outline-show-all’ instead.
Warning (bytecomp): ‘hide-sublevels’ is an obsolete function (as of 25.1); use ‘outline-hide-sublevels’ instead.
Warning (bytecomp): ‘show-entry’ is an obsolete function (as of 25.1); use ‘outline-show-entry’ instead.
Warning (bytecomp): ‘show-children’ is an obsolete function (as of 25.1); use ‘outline-show-children’ instead.
Warning (bytecomp): ‘show-subtree’ is an obsolete function (as of 25.1); use ‘outline-show-subtree’ instead.
Warning (bytecomp): ‘hide-subtree’ is an obsolete function (as of 25.1); use ‘outline-hide-subtree’ instead.
Warning (bytecomp): attempt to let-bind nonvariable ‘(lucr (msl--LUCR-filter-LaTeX-aliases lucr))’
Warning (bytecomp): assignment to free variable ‘company-math--unicode-prefix-regexp’
Warning (bytecomp): reference to free variable ‘company-math--unicode-prefix-regexp’ [2 times]
Warning (bytecomp): the function ‘assoc-delete-all’ is not known to be defined.
Warning (bytecomp): ‘eieio-object-name-string’ is an obsolete function (as of 25.1); use ‘eieio-named’ instead. [2 times]
Warning (bytecomp): looking-back called with 1 argument, but requires 2-3
Error (bytecomp): Cannot open load file: No such file or directory, cider
Error (bytecomp): Cannot open load file: No such file or directory, elm-mode
Error (bytecomp): Cannot open load file: No such file or directory, erlang
Error (bytecomp): Cannot open load file: No such file or directory, geiser-mode
Error (bytecomp): Cannot open load file: No such file or directory, hy-mode
Error (bytecomp): Cannot open load file: No such file or directory, elixir-mode
Error (bytecomp): Cannot open load file: No such file or directory, js-comint
Error (bytecomp): Cannot open load file: No such file or directory, lua-mode
Error (bytecomp): Cannot open load file: No such file or directory, tuareg
Warning (bytecomp): the function ‘prolog-consult-region’ is not known to be defined.
Warning (bytecomp): ‘python-shell-get-or-create-process’ is an obsolete function (as of 25.1); Instead call ‘python-shell-get-process’ and create one if returns nil.
Warning (bytecomp): ‘python-shell-parse-command’ is an obsolete function (as of 25.1); use ‘python-shell-calculate-command’ instead.
Error (bytecomp): Cannot open load file: No such file or directory, racket-mode
Error (bytecomp): Cannot open load file: No such file or directory, inf-ruby
Error (bytecomp): Cannot open load file: No such file or directory, slime
Error (bytecomp): Cannot open load file: No such file or directory, sly
Error (bytecomp): Cannot open load file: No such file or directory, sml-mode
Warning (bytecomp): Unused lexical variable ‘name-repl-buffer’
Warning (bytecomp): Unused lexical variable ‘name-script-buffer’
Warning (bytecomp): defcustom for ‘dumb-jump-ivy-jump-to-selected-function’ fails to specify type [2 times]
Warning (bytecomp): ‘find-tag-marker-ring’ is an obsolete variable (as of 25.1); use ‘xref-push-marker-stack’ or ‘xref-pop-marker-stack’ instead.
Warning (bytecomp): the function ‘helm-build-sync-source’ is not known to be defined.
Warning (bytecomp): ‘flycheck-disable-checker’ is for interactive use only; Directly set ‘flycheck-disabled-checkers’ instead
Warning (bytecomp): the following functions are not known to be defined: event-point,
    delete-extent, make-extent, set-extent-property,
    balloon-help-minor-mode
Warning (bytecomp): defcustom for ‘untitled-new-buffer-default-name’ fails to specify type [2 times]

In poetry-new:
poetry.el:403:11:Warning: reference to free variable ‘poetry-tracking-mode’

In poetry-venv-workon:
poetry.el:473:9:Warning: reference to free variable ‘poetry-tracking-mode’
poetry.el:479:1:Warning: Unused lexical variable ‘venv’

In poetry-venv-deactivate:
poetry.el:482:9:Warning: reference to free variable ‘poetry-tracking-mode’
poetry.el:546:11:Warning: Unused lexical argument ‘args’
poetry.el:546:11:Warning: Unused lexical argument ‘args’
poetry.el:671:1:Warning: Unused lexical argument ‘len’
`

`emacs --debug-init` report

`Debugger entered--Lisp error: (file-error "https://elpa.gnu.org/packages/archiv$
  signal(file-error ("https://elpa.gnu.org/packages/archive-contents" "Bad Requ$
  package--download-one-archive(("gnu" . "https://elpa.gnu.org/packages/") "arc$
  package--download-and-read-archives(nil)
  package-refresh-contents()
  (if (cl-every 'package-installed-p package-selected-packages) nil (message "M$
  eval-buffer(#<buffer  *load*> nil "/home/pi/.emacs.d/init.el" nil t)  ; Readi$
  load-with-code-conversion("/home/pi/.emacs.d/init.el" "/home/pi/.emacs.d/init$
  load("/home/pi/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0xaa6bf>)()`

Raspbian Buster. `emacs --version` show:
`GNU Emacs 26.1
Copyright (C) 2018 Free Software Foundation, Inc.`

But all packages are updated. Is there any newer version of Emacs for Raspbian?

**Comment by izahn** [comment]
Warnings are common when installing emacs packages in my experience. I just ignore them. Is anything broken or not working as expected?

**Comment by abunavas** [comment]
> Warnings are common when installing emacs packages in my experience. I just ignore them. Is anything broken or not working as expected?

Well I am totally n00b, I install it to learn, so I can't tell if anything is broken :-)

**Comment by izahn** [comment]
> 
> Well I am totally n00b, I install it to learn, so I can't tell if anything is broken :-)

Ah yes, and it definitely isn't a good first impression to see all those warnings! I'm not sure there's much we can do about it here though. We could try hiding them, but I'm not sure that's a great idea either.

**Comment by abunavas** [comment]
No, warnings are OK. The part of the learning process. So, it's fine to have Emacs 26.1, right?

**Comment by izahn** [comment]
Yes, Emacs 26 is fully supported.
