### ISSUE TITLE
latex mode

### ISSUE THREAD

**Issue by thegaryking** [IQSS/IQSS.emacs#7]
i have a file with .tex extension that, in case it is relevant, begins with the line:
\subsection*{}

when I load this in emacs, it doesn't recognize it as latex and doesn't turn on latex-mode.  Shouldn't it turn on latex-mode for any .tex file?  Can we put that in effect?

thanks

**Comment by izahn** [comment]
It will probably not surprise you to learn that I cannot reproduce this problem. If you think there is something about the particular file that causes problems please attach it here.

One possibility is that there is a space at the end of the file name.  Could that possibly be the issue?

**Comment by thegaryking** [comment]
here you go

Gary
--
*Gary King* - Albert J. Weatherhead III University Professor - Director,
IQSS <http://iq.harvard.edu/> - Harvard University
GaryKing.org - King@Harvard.edu - @KingGary <https://twitter.com/kinggary> -
617-500-7570 - Assistant <king-assist@iq.harvard.edu>: 617-495-9271

**Comment by izahn** [comment]
Incomplete file local variables cause Emacs to quit trying to determine what mode to open a file in. For example, in this case the file contained 

```
% Local Variables:
% TeX-engine: default
% TeX-master: 
% End:
```
Changing it to 


```
% Local Variables:
% TeX-engine: default
% TeX-master: nil 
% End:
```

solved the problem.
