### ISSUE TITLE
emacs dies on loading

### ISSUE THREAD

**Issue by thegaryking** [IQSS/IQSS.emacs#8]
after asking about anonconda-mode, and I answer Y, the load script apparently exits and it dies.  custom fonts etc are not loaded.  can you fix?

**Comment by izahn** [comment]
I can't reproduce on any of my machines. Is there an error message? Anything unusual in the `*Messages*` buffer? 
Can you run emacs with `--debug-init` and report any error messages here? (According to https://superuser.com/questions/458658/open-emacs-with-debug-init-on-os-x you can do this on a Mac by running `/Applications/Emacs.app/Contents/MacOS/emacs --debug-init` from the terminal.)

**Comment by thegaryking** [comment]
I get this:


then I hit 'y' and it immediately ends (sooner than it should I think) and
gives this:

Debugger entered--Lisp error: (error "Package ‘emacs-25.3’ is unavailable")
  signal(error ("Package ‘emacs-25.3’ is unavailable"))
  error("Package `%s-%s' is unavailable" emacs "25.3")
  package-compute-transaction(([cl-struct-package-desc minions (20180321
749) "A minor-mode menu for the mode line" ((emacs (25 3)) (dash (2 13 0)))
single "melpa" nil ((:commit . "536653d2dcae8362f2d02fee3ca8b65d4c875db7")
(:url . "https://github.com/tarsius/minions")) nil]) ((emacs (25 3)) (dash
(2 13 0))) ([cl-struct-package-desc minions (20180321 749) "A minor-mode
menu for the mode line" ((emacs (25 3)) (dash (2 13 0))) single "melpa" nil
((:commit . "536653d2dcae8362f2d02fee3ca8b65d4c875db7") (:url . "
https://github.com/tarsius/minions")) nil]))
  package-compute-transaction(nil ((minions)))
  package-install(minions dont-select)
  #[257 "\300 \301\"\207" [package-install dont-select] 4 "\n\n(fn
P)"](minions)
  mapc(#[257 "\300 \301\"\207" [package-install dont-select] 4 "\n\n(fn
P)"] (minions anaconda-mode company-anaconda))
  package-install-selected-packages()
  (if (every (quote package-installed-p) package-selected-packages) nil
(message "Missing packages detected, please wait...")
(package-refresh-contents) (package-install (car (cdr (assq (quote org)
package-archive-contents)))) (package-install-selected-packages))
  eval-buffer(#<buffer  *load*> nil "/Users/king/.emacs.d/init.el" nil t)
; Reading at buffer position 3051
  load-with-code-conversion("/Users/king/.emacs.d/init.el"
"/Users/king/.emacs.d/init.el" t t)
  load("/Users/king/.emacs.d/init" t t)
  #[0 " \205\266 \306=\203 \307 \310Q\202? \311=\204 \307
\312Q\202?\313\307\314\315#\203*\316\202?\313\307\314\317#\203>\320\321\322!D\nB
\323\202?\316\324 \325 \324\211#\210 \324=\203e\326\327\330\307
\331Q!\"\325 \324\211#\210 \324=\203d \210 \203\247\332
!\333\232\203\247\334 !\211\335P\336 !\203\201\211\202\214\336 !\203\213
\202\214\314\262 \203\245\337 \"\203\243\340\341 #\210\342\343!\210 \266
\f?\205\264\314 \325\344\324\211#)\262 \207" [init-file-user system-type
delayed-warnings-list user-init-file inhibit-default-init
inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs"
directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs"
"^_emacs\\(\\.elc?\\)?$" initialization format-message "`_emacs' init file
is deprecated, please use `.emacs'" "~/_emacs" t load expand-file-name
"init" file-name-as-directory "/.emacs.d" file-name-extension "elc"
file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message
"Warning: %s is newer than %s" sit-for 1 "default"] 7]()
  command-line()
  normal-top-level()


Gary
--
*Gary King* - Albert J. Weatherhead III University Professor - Director,
IQSS <http://iq.harvard.edu/> - Harvard University
GaryKing.org - King@Harvard.edu - @KingGary <https://twitter.com/kinggary> -
617-500-7570 - Assistant <king-assist@iq.harvard.edu>: 617-495-9271

**Comment by izahn** [comment]
That suggests that you need to update your Emacs. I've updated the code to give a more intuitive error in this case in commit 2ccf2a755490eb5942189dba6fedb9236197f76c

**Comment by thegaryking** [comment]
after updating emacs, it still dies without your error message; it says:

Warning (initialization): An error occurred while loading
‘/Users/king/.emacs.d/init.el’:

error: Unable to activate package ‘magit’.
Required package ‘ghub-20171207’ is unavailable

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.


Gary
--
*Gary King* - Albert J. Weatherhead III University Professor - Director,
IQSS <http://iq.harvard.edu/> - Harvard University
GaryKing.org - King@Harvard.edu - @KingGary <https://twitter.com/kinggary> -
617-500-7570 - Assistant <king-assist@iq.harvard.edu>: 617-495-9271

**Comment by izahn** [comment]
It turned out that updating packages fixed the problem. Since the answer to "it doesn't work" is usually "update something", I've opened https://github.com/IQSS/IQSS.emacs/issues/10 to remind us that we should add a troubleshooting section to the documentation.
